name: Build APK
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir app && unzip -q myket-game-project.zip -d app
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: npm install -g cordova@12
      - name: Build
        working-directory: app/myket-game
        run: |
          cordova platform add android@12
          cordova plugin add ./myket-iab-plugin
          cordova build android --release --buildConfig=build.json -- --packageType=apk
      - uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: app/myket-game/platforms/android/app/build/outputs/apk/release/*.apk
